/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package effectiveJava;

import effectiveJava.chap2.Chap2;

public class App {
    public static void main(String[] args) {
        Chap2.main();
    }
}
